//! An end-to-end test of the full pipeline, using only each crate's
//! public API, the same way `main.rs` does. Where the unit tests in each
//! crate check one piece in isolation, this test checks that the pieces
//! actually fit together: a signal generated by `strategy` can be sized
//! by `risk`, submitted through `broker`, and the resulting state
//! reconciled by `daemon::recovery`, all using the real types each crate
//! hands to the next one.

use broker::{BrokerAdapter, MockBroker};
use daemon::{allows_new_entries, apply_reconciliation, reconcile, HealthCheckFailure, HealthMonitor};
use domain::{Bias, Direction, OrderRequest, OrderType, Percent, Position, Tier, Usd};
use risk::RiskEngine as _;
use rust_decimal_macros::dec;
use strategy::{generate_signal, BufferLevels, DivergenceInputs, SignalOutcome};
use uuid::Uuid;

#[tokio::test]
async fn fresh_startup_reconciles_clean_against_an_empty_broker() {
    let broker = MockBroker::new(Usd::from_decimal(dec!(10000)), dec!(1.1000));
    let local: Vec<Position> = Vec::new();

    let report = reconcile(&broker, &local).await.unwrap();
    assert!(report.is_clean());
    assert!(apply_reconciliation(&report).is_empty());
}

#[tokio::test]
async fn a_full_cycle_goes_from_divergence_to_an_open_broker_position() {
    let broker = MockBroker::new(Usd::from_decimal(dec!(10000)), dec!(1.10000));

    let inputs = DivergenceInputs {
        primary_price: dec!(1.09900),
        secondary_price: dec!(1.10100),
        daily_primary_buffer: BufferLevels { low: dec!(1.10000), high: dec!(1.10500) },
        daily_secondary_buffer: BufferLevels { low: dec!(1.10000), high: dec!(1.10500) },
        session_primary_buffer: BufferLevels { low: dec!(1.09000), high: dec!(1.11000) },
        session_secondary_buffer: BufferLevels { low: dec!(1.09000), high: dec!(1.11000) },
    };

    let snapshot = broker
        .get_snapshot(&["EURUSD".to_string(), "GBPUSD".to_string()])
        .await
        .unwrap();

    let outcome = generate_signal(
        &inputs,
        Bias::Buy, // weekly agrees
        Bias::Sell,
        "GBPUSD".to_string(),
        "EURUSD".to_string(),
        snapshot.snapshot_id,
        dec!(0.8),
        dec!(0.8),
        snapshot.timestamp + chrono::Duration::minutes(20),
    );

    let signal = match outcome {
        SignalOutcome::Signal(signal) => signal,
        other => panic!("expected a passing signal in this fixture, got {other:?}"),
    };
    // primary_price sweeps the primary buffer's low while secondary_price
    // holds its own, so this divergence is about secondary (EURUSD): it's
    // the one that held, making it the relatively stronger asset to buy.
    assert_eq!(signal.pair, "EURUSD");

    let config = risk::RiskConfig {
        base_risk_percent: Percent::from_percentage(dec!(1.0)),
        max_risk_percent: Percent::from_percentage(dec!(5.0)),
        max_open_positions: 5,
        daily_loss_limit_percent: Percent::from_percentage(dec!(5.0)),
        weekly_loss_limit_percent: Percent::from_percentage(dec!(10.0)),
    };
    let context = risk::RiskContext {
        equity: broker.get_account_equity().await.unwrap(),
        open_position_count: 0,
        is_tuesday: false,
        is_double_smt: signal.tier == Tier::Double,
        entry_price: dec!(1.10000),
        stop_loss_price: dec!(1.09500),
        take_profit_price: dec!(1.11500),
        realized_pnl_today: Usd::zero(),
        realized_pnl_this_week: Usd::zero(),
    };

    let risk_engine = risk::DefaultRiskEngine;
    let decision = risk_engine.evaluate(&signal, &config, &context).unwrap();
    assert!(decision.approved);

    let request = OrderRequest {
        order_id: Uuid::new_v4(),
        trace_id: signal.trace_id,
        signal_id: signal.signal_id,
        pair: signal.pair.clone(),
        side: signal.direction,
        size: decision.position_size,
        order_type: OrderType::Market,
        price: None,
        stop_loss: Some(decision.stop_loss),
        take_profit: Some(decision.take_profit),
        confirming_snapshot_id: snapshot.snapshot_id,
    };

    let order = broker.submit_order(request).await.unwrap();
    assert_eq!(order.status, domain::OrderStatus::Filled);

    let open = broker.list_open_positions().await.unwrap();
    assert_eq!(open.len(), 1);
    assert_eq!(open[0].direction, Direction::Buy);

    // And reconciliation against this now-nonempty broker state should
    // adopt exactly this position when local state starts from nothing,
    // exactly the scenario a restart-after-crash would look like.
    let report = reconcile(&broker, &[]).await.unwrap();
    assert_eq!(report.unknown_to_local.len(), 1);
    let reconciled = apply_reconciliation(&report);
    assert_eq!(reconciled.len(), 1);
}

#[tokio::test]
async fn true_open_conflict_rejects_before_any_order_reaches_the_broker() {
    let broker = MockBroker::new(Usd::from_decimal(dec!(10000)), dec!(1.10000));

    let inputs = DivergenceInputs {
        primary_price: dec!(1.09900),
        secondary_price: dec!(1.10100),
        daily_primary_buffer: BufferLevels { low: dec!(1.10000), high: dec!(1.10500) },
        daily_secondary_buffer: BufferLevels { low: dec!(1.10000), high: dec!(1.10500) },
        session_primary_buffer: BufferLevels { low: dec!(1.09000), high: dec!(1.11000) },
        session_secondary_buffer: BufferLevels { low: dec!(1.09000), high: dec!(1.11000) },
    };

    let snapshot = broker
        .get_snapshot(&["EURUSD".to_string(), "GBPUSD".to_string()])
        .await
        .unwrap();

    // This divergence is bullish (Buy), but Weekly True Open is bearish:
    // a direct conflict that the gate should reject before risk sizing or
    // broker submission is ever reached.
    let outcome = generate_signal(
        &inputs,
        Bias::Sell,
        Bias::Sell,
        "GBPUSD".to_string(),
        "EURUSD".to_string(),
        snapshot.snapshot_id,
        dec!(0.8),
        dec!(0.8),
        snapshot.timestamp + chrono::Duration::minutes(20),
    );

    assert!(matches!(outcome, SignalOutcome::Rejected(_)));

    // Only the snapshot call above should have reached the broker: the
    // True Open gate rejects entirely within strategy::generate_signal,
    // a pure function that never touches the broker. Capturing the count
    // here, before the verification call just below, matters: calling
    // list_open_positions to check the assertion would itself add a
    // second call and make this check meaningless.
    assert_eq!(broker.how_many_calls(), 1, "only the snapshot call should have reached the broker");

    let open = broker.list_open_positions().await.unwrap();
    assert!(open.is_empty());
}

#[tokio::test]
async fn broker_heartbeat_failure_blocks_new_entries_until_cleared() {
    let health = HealthMonitor::new();
    assert!(allows_new_entries(health.current_state()));

    health.report_failure(HealthCheckFailure::BrokerHeartbeatFailure);
    assert!(!allows_new_entries(health.current_state()));

    health.clear_failure(HealthCheckFailure::BrokerHeartbeatFailure);
    assert!(allows_new_entries(health.current_state()));
}
